#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Get current session name if we're in tmux
    current_session=""
    if [[ -n $TMUX ]]; then
        current_session=$(tmux display-message -p '#S')
    fi
    
    # Find all directories
    all_dirs=$(find ~/work -mindepth 1 -maxdepth 1 -type d)
    
    if [[ -n $current_session ]]; then
        # Convert current session name back to directory path
        current_dir=""
        while IFS= read -r dir; do
            dir_name=$(basename "$dir" | tr . _)
            if [[ "$dir_name" == "$current_session" ]]; then
                current_dir="$dir"
                break
            fi
        done <<< "$all_dirs"
        
        # If we found the current directory, put it last, with others first
        if [[ -n $current_dir ]]; then
            other_dirs=$(echo "$all_dirs" | grep -v "^$current_dir$")
            selected=$(printf "%s\n%s" "$other_dirs" "$current_dir" | fzf --header="Current session: $current_session")
        else
            selected=$(echo "$all_dirs" | fzf)
        fi
    else
        selected=$(echo "$all_dirs" | fzf)
    fi
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
